#!/usr/bin/env bash
#
# catalog.sh — generate a human-readable catalogue of every wired skill.
#
# Scans every SKILL.md (root-owned + submodules), pulls `name` and
# `description` from the YAML frontmatter, and writes SKILLS.md grouped by
# source. Output is deterministic (entries sorted by name, no timestamp) so
# re-running produces an identical file unless the skills themselves change.
#
# Usage:
#   bash catalog.sh            # write SKILLS.md in the repo root
#   bash catalog.sh /tmp/x.md  # write somewhere else (used by tests)
#
# Re-run after adding, editing, or updating skills — same idea as wire.sh.

set -euo pipefail

# Repo root: this script's own directory unless GRID_DIR overrides it.
GRID_DIR="${GRID_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
OUT="${1:-$GRID_DIR/SKILLS.md}"

# --- Parse one SKILL.md → prints "name<TAB>summary" ------------------------
# Handles inline, quoted, folded (>) and block (|) YAML scalars for the
# description, plus plain multi-line continuations. The "summary" is the first
# sentence of the description, capped for readability.
parse_skill() {
  awk '
    function trim(s){ sub(/^[[:space:]]+/,"",s); sub(/[[:space:]]+$/,"",s); return s }
    BEGIN { fm=0; coll=0; name=""; desc="" }
    {
      # Frontmatter fence: first --- opens, second --- closes.
      if ($0 ~ /^---[[:space:]]*$/) {
        if (fm==0) { fm=1; next }
        else if (fm==1) { fm=2; exit }
      }
      if (fm!=1) next

      # Collecting continuation lines of a description block.
      if (coll==1) {
        if ($0 ~ /^[[:space:]]/) { desc=desc " " trim($0); next }
        else { coll=0 }   # de-indented line ends the block; re-parse it below
      }

      if ($0 ~ /^name:/) {
        v=$0; sub(/^name:[[:space:]]*/,"",v); v=trim(v)
        gsub(/^["'\'']|["'\'']$/,"",v); name=v; next
      }
      if ($0 ~ /^description:/) {
        v=$0; sub(/^description:[[:space:]]*/,"",v); v=trim(v)
        # Block/folded indicators (>, |, with optional +/-) → gather next lines.
        if (v ~ /^[>|][+-]?$/ || v=="") { coll=1; desc="" }
        else { gsub(/^["'\'']|["'\'']$/,"",v); desc=v; coll=1 }
        next
      }
    }
    END {
      desc=trim(desc)
      # Quick summary = first sentence (up to ". "), else the whole thing.
      summary=desc
      if (match(desc, /\. /)) summary=substr(desc, 1, RSTART)
      summary=trim(summary)
      # Cap length so the catalogue stays skimmable.
      if (length(summary) > 200) summary=substr(summary,1,199) "\xe2\x80\xa6"
      print name "\t" summary
    }
  ' "$1"
}

# --- Emit a markdown section for a list of skill dirs ----------------------
# Reads NUL-free SKILL.md paths on stdin (one per line), sorts by skill name,
# prints "- **name** — summary" bullets. Returns the count via a global.
SECTION_COUNT=0
emit_section() {
  local title="$1"; shift
  local lines=() path name summary base
  while IFS= read -r path; do
    [ -n "$path" ] || continue
    IFS=$'\t' read -r name summary < <(parse_skill "$path")
    base="$(basename "$(dirname "$path")")"
    [ -n "$name" ] || name="$base"                 # fall back to dir name
    [ -n "$summary" ] || summary="_(no description)_"
    # Sort key is the skill name (case-insensitive), payload is the bullet.
    lines+=("$(printf '%s\t- **%s** — %s' "$name" "$name" "$summary")")
  done
  SECTION_COUNT=${#lines[@]}
  printf '## %s — %s\n\n' "$title" "$SECTION_COUNT"
  if [ "$SECTION_COUNT" -gt 0 ]; then
    printf '%s\n' "${lines[@]}" | sort -f | cut -f2-
  else
    printf '_none_\n'
  fi
  printf '\n'
}

# --- Find SKILL.md files for a given root, skipping a repo-root SKILL.md ---
find_skills() {
  find "$1" -name SKILL.md -not -path '*/.git/*' 2>/dev/null
}

# --- Build the document into a buffer, then write once ---------------------
total=$(find "$GRID_DIR" -name SKILL.md -not -path '*/.git/*' | wc -l | tr -d ' ')

{
  printf '# the-grid — skill catalogue\n\n'
  printf '> Generated by `catalog.sh` from each skill'\''s `SKILL.md` frontmatter.\n'
  printf '> **Do not edit by hand** — re-run `bash catalog.sh` after adding or updating skills.\n\n'
  printf '**%s skills** — %s root-owned, the rest pulled from submodules under `repos/`.\n\n' \
    "$total" "$(find "$GRID_DIR" -maxdepth 2 -name SKILL.md -not -path "$GRID_DIR/repos/*" -not -path '*/.git/*' | wc -l | tr -d ' ')"

  # Root-owned skills first (top-level dirs containing a SKILL.md).
  emit_section "Root (owned / edited)" < <(
    for d in "$GRID_DIR"/*/; do
      [ -f "$d/SKILL.md" ] && printf '%s\n' "$d/SKILL.md"
    done
  )

  # Each submodule as its own section, alphabetical.
  for repo in "$GRID_DIR"/repos/*/; do
    [ -d "$repo" ] || continue
    name="$(basename "$repo")"
    emit_section "repos/$name" < <(find_skills "$repo")
  done
} > "$OUT"

echo "Wrote $OUT ($total skills)."
