#!/usr/bin/env bats
# Tests for agent-factory/deploy.py (per-project agent deploy) and the lean
# profile. Needs the agent-factory venv; skipped where it isn't built. Every
# test deploys into a temp project dir — never the real repo or ~/.claude.

load helpers/setup

setup() {
  common_setup
  PY="$REPO_ROOT/agent-factory/.venv/bin/python"
  [ -x "$PY" ] || skip "agent-factory venv not built"
  DEPLOY="$REPO_ROOT/agent-factory/deploy.py"
  PROJ=$(mktemp -d)
}

teardown() {
  rm -rf "$PROJ"
  common_teardown
}

@test "deploys a specialist and an orchestrator to the right places" {
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,tech-lead
  [ "$status" -eq 0 ]
  [ -f "$PROJ/.claude/agents/grid-qa-engineer.md" ]
  [ -f "$PROJ/.claude/skills/grid-tech-lead/SKILL.md" ]
  [ -f "$PROJ/.claude/grid-agents.lock" ]
  grep -q "GENERATED by the-grid" "$PROJ/.claude/agents/grid-qa-engineer.md"
}

@test "lean profile is smaller than full and drops the boot sequence" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --profile lean
  lean=$(wc -c < "$PROJ/.claude/agents/grid-qa-engineer.md")
  ! grep -q "Boot Sequence" "$PROJ/.claude/agents/grid-qa-engineer.md" || false
  grep -q "Operating procedure" "$PROJ/.claude/agents/grid-qa-engineer.md"
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --profile full
  full=$(wc -c < "$PROJ/.claude/agents/grid-qa-engineer.md")
  [ "$lean" -lt "$full" ]
  grep -q "Boot Sequence" "$PROJ/.claude/agents/grid-qa-engineer.md"
}

@test "re-running is a byte-for-byte no-op" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  before=$(find "$PROJ" -type f -exec shasum {} + | sort)
  run "$PY" "$DEPLOY" "$PROJ"          # roles + profile come from the lock
  [ "$status" -eq 0 ]
  [[ "$output" == *"0 written"* ]]
  [ "$before" = "$(find "$PROJ" -type f -exec shasum {} + | sort)" ]
}

@test "refuses to overwrite a hand-written agent and writes nothing" {
  mkdir -p "$PROJ/.claude/agents"
  echo "my own agent" > "$PROJ/.claude/agents/grid-qa-engineer.md"
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  [ "$status" -eq 1 ]
  [[ "$output" == *"hand-written"* ]]
  [ "$(cat "$PROJ/.claude/agents/grid-qa-engineer.md")" = "my own agent" ]
  [ ! -e "$PROJ/.claude/agents/grid-backend-dev.md" ]    # validated before any write
  [ ! -e "$PROJ/.claude/grid-agents.lock" ]
}

@test "project.yaml context is injected into every agent, per-role extras only into theirs" {
  mkdir -p "$PROJ/.grid"
  printf 'context: |\n  SHARED-FACT\nroles:\n  qa-engineer: |\n    QA-ONLY-FACT\n' > "$PROJ/.grid/project.yaml"
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  grep -q "SHARED-FACT" "$PROJ/.claude/agents/grid-qa-engineer.md"
  grep -q "SHARED-FACT" "$PROJ/.claude/agents/grid-backend-dev.md"
  grep -q "QA-ONLY-FACT" "$PROJ/.claude/agents/grid-qa-engineer.md"
  ! grep -q "QA-ONLY-FACT" "$PROJ/.claude/agents/grid-backend-dev.md" || false
}

@test "context for a role that is not deployed is an error" {
  mkdir -p "$PROJ/.grid"
  printf 'roles:\n  sdet: |\n    x\n' > "$PROJ/.grid/project.yaml"
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  [ "$status" -eq 1 ]
  [[ "$output" == *"sdet"* ]]
}

@test "--check reports a hand-edit and does not repair it" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  echo "edited" >> "$PROJ/.claude/agents/grid-qa-engineer.md"
  run "$PY" "$DEPLOY" "$PROJ" --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"stale"* ]]
  grep -q edited "$PROJ/.claude/agents/grid-qa-engineer.md"
}

@test "dropping a role from --roles removes only its generated file" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  [ "$status" -eq 0 ]
  [ ! -e "$PROJ/.claude/agents/grid-backend-dev.md" ]
  [ -f "$PROJ/.claude/agents/grid-qa-engineer.md" ]
}

@test "a hand-edited stale file is left alone when its role is dropped" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  echo "no marker now" > "$PROJ/.claude/agents/grid-backend-dev.md"
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  [ "$(cat "$PROJ/.claude/agents/grid-backend-dev.md")" = "no marker now" ]
}

@test "orchestrator roster lists only delegates deployed alongside it" {
  "$PY" "$DEPLOY" "$PROJ" --roles tech-lead,backend-dev
  f="$PROJ/.claude/skills/grid-tech-lead/SKILL.md"
  grep -q "grid-backend-dev" "$f"
  ! grep -q "grid-frontend-dev" "$f" || false
}

@test "unknown role and missing roles are errors" {
  run "$PY" "$DEPLOY" "$PROJ" --roles nope
  [ "$status" -eq 1 ]
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 1 ]
}

@test "refuses to deploy into the-grid itself" {
  run "$PY" "$DEPLOY" "$REPO_ROOT" --roles qa-engineer
  [ "$status" -eq 1 ]
  [[ "$output" == *"the-grid itself"* ]]
}
