#!/usr/bin/env bats
# Tests for agent-factory/deploy.py (per-project agent deploy) and the lean
# profile. Needs the agent-factory venv; skipped where it isn't built. Every
# test deploys into a temp project dir — never the real repo or ~/.claude.

load helpers/setup

setup() {
  common_setup
  PY="$REPO_ROOT/agent-factory/.venv/bin/python"
  [ -x "$PY" ] || skip "agent-factory venv not built"
  DEPLOY="$REPO_ROOT/agent-factory/deploy.py"
  PROJ=$(mktemp -d)
}

teardown() {
  rm -rf "$PROJ"
  common_teardown
}

@test "deploys a specialist and an orchestrator to the right places" {
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,tech-lead
  [ "$status" -eq 0 ]
  [ -f "$PROJ/.claude/agents/grid-qa-engineer.md" ]
  [ -f "$PROJ/.claude/skills/grid-tech-lead/SKILL.md" ]
  [ -f "$PROJ/.claude/grid-agents.lock" ]
  grep -q "GENERATED by the-grid" "$PROJ/.claude/agents/grid-qa-engineer.md"
}

@test "lean profile is smaller than full and drops the boot sequence" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --profile lean
  lean=$(wc -c < "$PROJ/.claude/agents/grid-qa-engineer.md")
  ! grep -q "Boot Sequence" "$PROJ/.claude/agents/grid-qa-engineer.md" || false
  grep -q "Operating procedure" "$PROJ/.claude/agents/grid-qa-engineer.md"
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --profile full
  full=$(wc -c < "$PROJ/.claude/agents/grid-qa-engineer.md")
  [ "$lean" -lt "$full" ]
  grep -q "Boot Sequence" "$PROJ/.claude/agents/grid-qa-engineer.md"
}

@test "re-running is a byte-for-byte no-op" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  before=$(find "$PROJ" -type f -exec shasum {} + | sort)
  run "$PY" "$DEPLOY" "$PROJ"          # roles + profile come from the lock
  [ "$status" -eq 0 ]
  [[ "$output" == *"0 written"* ]] || false
  [ "$before" = "$(find "$PROJ" -type f -exec shasum {} + | sort)" ]
}

@test "refuses to overwrite a hand-written agent and writes nothing" {
  mkdir -p "$PROJ/.claude/agents"
  echo "my own agent" > "$PROJ/.claude/agents/grid-qa-engineer.md"
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  [ "$status" -eq 1 ]
  [[ "$output" == *"hand-written"* ]] || false
  [ "$(cat "$PROJ/.claude/agents/grid-qa-engineer.md")" = "my own agent" ]
  [ ! -e "$PROJ/.claude/agents/grid-backend-dev.md" ]    # validated before any write
  [ ! -e "$PROJ/.claude/grid-agents.lock" ]
}

@test "project.yaml context is injected into every agent, per-role extras only into theirs" {
  mkdir -p "$PROJ/.grid"
  printf 'context: |\n  SHARED-FACT\nroles:\n  qa-engineer: |\n    QA-ONLY-FACT\n' > "$PROJ/.grid/project.yaml"
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  grep -q "SHARED-FACT" "$PROJ/.claude/agents/grid-qa-engineer.md"
  grep -q "SHARED-FACT" "$PROJ/.claude/agents/grid-backend-dev.md"
  grep -q "QA-ONLY-FACT" "$PROJ/.claude/agents/grid-qa-engineer.md"
  ! grep -q "QA-ONLY-FACT" "$PROJ/.claude/agents/grid-backend-dev.md" || false
}

@test "context for a role that is not deployed is an error" {
  mkdir -p "$PROJ/.grid"
  printf 'roles:\n  sdet: |\n    x\n' > "$PROJ/.grid/project.yaml"
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  [ "$status" -eq 1 ]
  [[ "$output" == *"sdet"* ]] || false
}

@test "--check reports a hand-edit and does not repair it" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  echo "edited" >> "$PROJ/.claude/agents/grid-qa-engineer.md"
  run "$PY" "$DEPLOY" "$PROJ" --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"stale"* ]] || false
  grep -q edited "$PROJ/.claude/agents/grid-qa-engineer.md"
}

@test "dropping a role from --roles removes only its generated file" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  [ "$status" -eq 0 ]
  [ ! -e "$PROJ/.claude/agents/grid-backend-dev.md" ]
  [ -f "$PROJ/.claude/agents/grid-qa-engineer.md" ]
}

@test "a hand-edited stale file is left alone when its role is dropped" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  echo "no marker now" > "$PROJ/.claude/agents/grid-backend-dev.md"
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer
  [ "$(cat "$PROJ/.claude/agents/grid-backend-dev.md")" = "no marker now" ]
}

@test "orchestrator roster lists only delegates deployed alongside it" {
  "$PY" "$DEPLOY" "$PROJ" --roles tech-lead,backend-dev
  f="$PROJ/.claude/skills/grid-tech-lead/SKILL.md"
  grep -q "grid-backend-dev" "$f"
  ! grep -q "grid-frontend-dev" "$f" || false
}

@test "unknown role and missing roles are errors" {
  run "$PY" "$DEPLOY" "$PROJ" --roles nope
  [ "$status" -eq 1 ]
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 1 ]
}

@test "refuses to deploy into the-grid itself" {
  run "$PY" "$DEPLOY" "$REPO_ROOT" --roles qa-engineer
  [ "$status" -eq 1 ]
  [[ "$output" == *"the-grid itself"* ]] || false
}

# --- hardening (from the security / QA review) --------------------------------

@test "a lock file listing paths outside .claude/{agents,skills} is refused and deletes nothing" {
  mkdir -p "$OTHER_DIR/victim"
  printf '%s\n' "$(printf '<!-- GENERATED by the-grid agent-factory/deploy.py — do not edit; re-run deploy.py -->')" > "$OTHER_DIR/victim/x"
  mkdir -p "$PROJ/.claude"
  printf '{"roles":["sdet"],"profile":"lean","files":{"%s":"x","../victim/x":"x"}}' "$OTHER_DIR/victim/x" > "$PROJ/.claude/grid-agents.lock"
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 1 ]
  [[ "$output" == *"out-of-bounds"* ]] || false
  [ -f "$OTHER_DIR/victim/x" ]
}

@test "a symlinked .claude/agents is refused and nothing is written through it" {
  mkdir -p "$PROJ/.claude" "$OTHER_DIR/outside"
  ln -s "$OTHER_DIR/outside" "$PROJ/.claude/agents"
  run "$PY" "$DEPLOY" "$PROJ" --roles sdet
  [ "$status" -eq 1 ]
  [[ "$output" == *"symlink"* ]] || false
  [ -z "$(ls -A "$OTHER_DIR/outside")" ]
}

@test "a lock of the wrong JSON shape gives a clear error, not a crash or char-split roles" {
  mkdir -p "$PROJ/.claude"
  echo '[]' > "$PROJ/.claude/grid-agents.lock"
  run "$PY" "$DEPLOY" "$PROJ" --roles sdet
  [ "$status" -eq 1 ]
  [[ "$output" == *"corrupt lock file"* ]] || false
  echo '{"roles":"sdet"}' > "$PROJ/.claude/grid-agents.lock"
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 1 ]
  [[ "$output" == *"corrupt lock file"* ]] || false
}

@test "a file that only MENTIONS the marker is not treated as generated" {
  mkdir -p "$PROJ/.claude/agents"
  printf 'notes: the marker is "GENERATED by the-grid agent-factory/deploy.py — do not edit; re-run deploy.py" ok\n' > "$PROJ/.claude/agents/grid-sdet.md"
  run "$PY" "$DEPLOY" "$PROJ" --roles sdet
  [ "$status" -eq 1 ]
  [[ "$output" == *"hand-written"* ]] || false
}

@test "deployed files are world-readable (0644), not mkstemp's 0600" {
  "$PY" "$DEPLOY" "$PROJ" --roles sdet
  [ "$(stat -f %Lp "$PROJ/.claude/agents/grid-sdet.md" 2>/dev/null || stat -c %a "$PROJ/.claude/agents/grid-sdet.md")" = "644" ]
}

@test "a symlinked grid-* skill dir cannot redirect writes outside the project" {
  mkdir -p "$PROJ/.claude/skills" "$OTHER_DIR/outside"
  ln -s "$OTHER_DIR/outside" "$PROJ/.claude/skills/grid-tech-lead"
  run "$PY" "$DEPLOY" "$PROJ" --roles tech-lead
  [ "$status" -eq 1 ]
  [[ "$output" == *"symlink"* ]] || false
  [ -z "$(ls -A "$OTHER_DIR/outside")" ]
}

@test "a symlinked grid-* skill dir cannot redirect stale removal outside the project" {
  mkdir -p "$PROJ/.claude/skills" "$OTHER_DIR/outside"
  printf -- '---\nname: x\n---\n<!-- GENERATED by the-grid agent-factory/deploy.py — do not edit; re-run deploy.py -->\n' > "$OTHER_DIR/outside/SKILL.md"
  ln -s "$OTHER_DIR/outside" "$PROJ/.claude/skills/grid-zz"
  printf '{"roles":["sdet"],"profile":"lean","files":{".claude/skills/grid-zz/SKILL.md":"x"}}' > "$PROJ/.claude/grid-agents.lock"
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 1 ]
  [ -f "$OTHER_DIR/outside/SKILL.md" ]
}

@test "a lock key ending in a newline is rejected (regex must fullmatch)" {
  mkdir -p "$PROJ/.claude"
  printf '{"roles":["sdet"],"profile":"lean","files":{".claude/agents/grid-x.md\\n":"x"}}' > "$PROJ/.claude/grid-agents.lock"
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 1 ]
  [[ "$output" == *"out-of-bounds"* ]] || false
}

@test "a symlinked lock file is refused" {
  mkdir -p "$PROJ/.claude"
  echo '{}' > "$OTHER_DIR/lock"
  ln -s "$OTHER_DIR/lock" "$PROJ/.claude/grid-agents.lock"
  run "$PY" "$DEPLOY" "$PROJ" --roles sdet
  [ "$status" -eq 1 ]
  [[ "$output" == *"symlink"* ]] || false
}

# --- profile inheritance / --check coverage (from the SDET review) -------------

@test "a bare re-run keeps the locked profile (full stays full)" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --profile full
  run "$PY" "$DEPLOY" "$PROJ"
  [ "$status" -eq 0 ]
  [[ "$output" == *"0 written"* ]] || false
  grep -q "Boot Sequence" "$PROJ/.claude/agents/grid-qa-engineer.md"
  grep -q '"profile": "full"' "$PROJ/.claude/grid-agents.lock"
}

@test "switching full to lean and re-running leaves no residue" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --profile full
  "$PY" "$DEPLOY" "$PROJ" --profile lean
  before=$(find "$PROJ" -type f -exec shasum {} + | sort)
  run "$PY" "$DEPLOY" "$PROJ"
  [[ "$output" == *"0 written"* ]] || false
  [ "$before" = "$(find "$PROJ" -type f -exec shasum {} + | sort)" ]
}

@test "--check on a clean deploy exits 0 and changes nothing" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  before=$(find "$PROJ" -type f -exec shasum {} + | sort)
  run "$PY" "$DEPLOY" "$PROJ" --check
  [ "$status" -eq 0 ]
  [[ "$output" == *"matches the grid"* ]] || false
  [ "$before" = "$(find "$PROJ" -type f -exec shasum {} + | sort)" ]
}

@test "--check reports a missing file" {
  "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer,backend-dev
  rm "$PROJ/.claude/agents/grid-backend-dev.md"
  run "$PY" "$DEPLOY" "$PROJ" --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"missing"* ]] || false
  [ ! -e "$PROJ/.claude/agents/grid-backend-dev.md" ]
}

@test "--check on a never-deployed project fails and writes nothing" {
  run "$PY" "$DEPLOY" "$PROJ" --roles qa-engineer --check
  [ "$status" -eq 1 ]
  [ -z "$(ls -A "$PROJ")" ]
}
