#!/usr/bin/env python3
"""deploy.py — deploy chosen grid agents into one project's own .claude/ dir.

The grid's composed agents are global (wire.sh links them into ~/.claude). This
deploys a *selection* of roles into <project>/.claude/ instead, so a project (or
a machine that wants no global grid at all) carries only the agents it needs.
Nothing is forked: every deployed file is rendered from the same role sources
compose.py uses, so there is no second copy of any role to drift.

Usage:
    deploy.py <project-dir> --roles qa-engineer,sdet [--profile lean|full]
    deploy.py <project-dir>            # re-deploy whatever the lock file lists
    deploy.py <project-dir> --check    # drift report; writes nothing; exit 1 on drift
    deploy.py --list                   # roles available to deploy
    --dry-run                          # show what would be written, write nothing

What lands in <project-dir>:
    .claude/agents/grid-<role>.md          specialist roles (subagents)
    .claude/skills/grid-<role>/SKILL.md    orchestrator roles (skills)
    .claude/grid-reference/grid-<role>.md  lean only: the SKILL's templates/checklists,
                                           read on demand instead of riding in the prompt
    .claude/grid-agents.lock               JSON: profile, roles, per-file sha256,
                                           grid commit — makes re-runs auditable

Project facts (real paths, commands, invariants, what exists vs. is planned)
come from an optional <project-dir>/.grid/project.yaml, never from the grid:
    context: |        # markdown given to every deployed agent
      ...
    roles:
      sdet: |         # extra markdown for one role
        ...

Trust: .grid/project.yaml text is written verbatim into the deployed agents'
system prompts. Anyone who can commit to the project can steer its agents through
it — treat it like CLAUDE.md (trusted, reviewed input), never as untrusted data.

Safety:
  - every generated file carries a GENERATED marker; a file without it is never
    overwritten or deleted (hand-written agents are safe) — the run aborts first
  - writes are validated up front, then applied atomically (temp file + rename)
  - re-running with unchanged inputs is a byte-for-byte no-op
"""

from __future__ import annotations

import argparse
import re
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import compose  # same dir; compose.main() is guarded by __name__

PREFIX = "grid"
MARKER = "<!-- GENERATED by the-grid agent-factory/deploy.py — do not edit; re-run deploy.py -->"
LOCK_REL = Path(".claude/grid-agents.lock")
CONTEXT_REL = Path(".grid/project.yaml")
GRID_ROOT = compose.HERE.parent.resolve()


def die(msg: str) -> "None":
    print(f"deploy: {msg}", file=sys.stderr)
    sys.exit(1)


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def grid_commit() -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(GRID_ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


# ── role index: which compose config defines each role's agent entry ──────────
def build_index() -> dict[str, dict]:
    """{role: agent entry} from every examples/*.yaml (delegates_to, stacks,
    skills, model overrides live there). A role defined by two configs is an
    error: the deploy would have to guess which wins."""
    index: dict[str, dict] = {}
    for cfg_path in sorted((compose.HERE / "examples").glob("*.yaml")):
        try:
            cfg = compose.load_config(cfg_path)
        except ValueError:
            continue  # e.g. a private desk whose roles are unreachable here
        for agent in cfg["agents"]:
            role = agent["role"]
            if role in index:
                die(f"role '{role}' is defined by more than one compose config; cannot pick one")
            index[role] = agent
    return index


# ── project context ───────────────────────────────────────────────────────────
def load_context(project: Path) -> tuple[str, dict[str, str]]:
    path = project / CONTEXT_REL
    if not path.is_file():
        return "", {}
    try:
        data = compose.yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except compose.yaml.YAMLError as exc:
        die(f"{path}: invalid YAML: {str(exc).splitlines()[0]}")
    if not isinstance(data, dict):
        die(f"{path}: must be a mapping")
    unknown = set(data) - {"project", "context", "roles"}
    if unknown:
        die(f"{path}: unknown key(s) {sorted(unknown)} (allowed: project, context, roles)")
    roles = data.get("roles") or {}
    if not isinstance(roles, dict):
        die(f"{path}: 'roles' must be a mapping of role -> markdown")
    return str(data.get("context") or ""), {k: str(v or "") for k, v in roles.items()}


# ── rendering ─────────────────────────────────────────────────────────────────
def with_marker(text: str) -> str:
    """Insert the GENERATED marker on the line after the frontmatter block."""
    end = text.index("\n---\n", 4) + len("\n---\n")
    return text[:end] + MARKER + "\n" + text[end:]


def render_all(roles: list[str], profile: str, index: dict[str, dict],
               shared_ctx: str, role_ctx: dict[str, str]) -> dict[str, str]:
    """{path relative to project dir: contents} for every selected role."""
    files: dict[str, str] = {}
    selected = set(roles)
    for role in roles:
        base = index[role]
        # An orchestrator's roster may only name delegates that are deployed too.
        agent = dict(base)
        if base.get("delegates_to") is not None:
            agent["delegates_to"] = [d for d in base["delegates_to"] if d in selected]
        ctx = "\n\n".join(x.strip() for x in (shared_ctx, role_ctx.get(role, "")) if x.strip())
        name = f"{PREFIX}-{role}"
        # Lean: template/checklist sections of the SKILL move to a reference file the
        # agent reads on demand, instead of riding in every prompt.
        ref_text = compose.lean_reference(role) if profile == "lean" else ""
        ref_rel = compose.REFERENCE_REL.format(name=name) if ref_text else ""
        if ref_text:
            title = compose.role_meta(role).get("title") or role
            files[ref_rel] = MARKER + f"\n# Reference — {title}\n\nTemplates and checklists for the `{name}` procedure.\n\n" + ref_text
        if compose.is_orchestrator(role):
            body = compose.emit_cc_skill(agent, PREFIX, profile, ctx, ref_rel)["SKILL.md"]
            files[f".claude/skills/{name}/SKILL.md"] = with_marker(body)
        else:
            fname, body = compose.emit_cc_subagent(agent, PREFIX, profile, ctx, ref_rel)
            files[f".claude/agents/{fname}"] = with_marker(body)
    return files


# ── lock file ─────────────────────────────────────────────────────────────────
# Paths a lock may legitimately list: exactly what render_all produces.
LOCK_PATH_RE = re.compile(
    r"\.claude/(agents/grid-[a-z0-9-]+\.md|skills/grid-[a-z0-9-]+/SKILL\.md|grid-reference/grid-[a-z0-9-]+\.md)"
)


def read_lock(project: Path) -> dict | None:
    """Parse and validate the lock. The lock is project-controlled (committed to
    the repo), so it is untrusted: every field is type-checked and every listed
    path must match the exact shape deploy.py writes, so a tampered lock can
    never point stale-file removal outside <project>/.claude/{agents,skills}."""
    path = project / LOCK_REL
    if path.is_symlink():
        die(f"refusing: {path} is a symlink")
    if not path.is_file():
        return None
    try:
        lock = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        die(f"{path}: corrupt lock file ({exc})")
    if not isinstance(lock, dict):
        die(f"{path}: corrupt lock file (not a JSON object)")
    roles, files = lock.get("roles", []), lock.get("files", {})
    if not (isinstance(roles, list) and all(isinstance(r, str) for r in roles)):
        die(f"{path}: corrupt lock file ('roles' must be a list of strings)")
    if lock.get("profile", "lean") not in compose.PROFILES:
        die(f"{path}: corrupt lock file (unknown profile {lock.get('profile')!r})")
    if not isinstance(files, dict):
        die(f"{path}: corrupt lock file ('files' must be an object)")
    bad = [k for k in files if not (isinstance(k, str) and LOCK_PATH_RE.fullmatch(k))]
    if bad:
        die(f"{path}: refusing lock file with out-of-bounds path(s): {', '.join(map(repr, bad))}")
    return lock


def assert_inside(project: Path, target: Path) -> None:
    """Die if any existing component between <project> and <target> (target's own
    name included) is a symlink. Called immediately before every write, unlink and
    rmdir, so a symlinked grid-* skill dir committed into a repo can't redirect
    them outside the project. (A racing local attacker could still swap a path
    between this check and the syscall; that needs a concurrent process on the
    same machine and is accepted.)"""
    rel = target.relative_to(project)
    cur = project
    for part in rel.parts:
        cur = cur / part
        if cur.is_symlink():
            die(f"refusing: {cur} is a symlink (would write/delete outside the project)")


def check_no_symlinks(project: Path) -> None:
    """Refuse to write through symlinked .claude, .claude/agents or .claude/skills
    (a link there would redirect the writes — and the deletes — elsewhere)."""
    for rel in (".claude", ".claude/agents", ".claude/skills", ".grid"):
        if (project / rel).is_symlink():
            die(f"refusing: {project / rel} is a symlink")


def lock_text(profile: str, roles: list[str], files: dict[str, str]) -> str:
    # No timestamp: an unchanged deploy must be byte-identical.
    return json.dumps({
        "generated_by": "the-grid agent-factory/deploy.py",
        "grid_commit": grid_commit(),
        "profile": profile,
        "roles": sorted(roles),
        "files": {rel: sha(txt) for rel, txt in sorted(files.items())},
    }, indent=2) + "\n"


# ── apply ─────────────────────────────────────────────────────────────────────
def is_generated(path: Path) -> bool:
    """True only if the marker is a whole line near the top (where with_marker puts
    it) — a source file that merely mentions the marker string does not count."""
    try:
        if path.is_symlink() or not path.is_file():
            return False
        head = path.read_text(encoding="utf-8").splitlines()[:20]
    except (OSError, UnicodeDecodeError):
        return False
    return MARKER in head


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".grid-deploy-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.chmod(tmp, 0o644)          # mkstemp creates 0600; deployed files are normal repo files
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("project", nargs="?", type=Path, help="target project directory")
    ap.add_argument("--roles", help="comma-separated roles (default: whatever the lock lists)")
    ap.add_argument("--profile", choices=compose.PROFILES, help="default: lock's profile, else lean")
    ap.add_argument("--check", action="store_true", help="report drift; write nothing")
    ap.add_argument("--dry-run", action="store_true", help="show the plan; write nothing")
    ap.add_argument("--list", action="store_true", help="list deployable roles and exit")
    args = ap.parse_args()

    index = build_index()
    if args.list:
        for role in sorted(index):
            kind = "skill" if compose.is_orchestrator(role) else "subagent"
            print(f"{role:<22} {kind:<9} {compose.role_summary(role)[:70]}")
        return
    if args.project is None:
        ap.error("project directory is required")
    project = args.project.expanduser().resolve()
    if not project.is_dir():
        die(f"{project} is not a directory")
    if project == GRID_ROOT or GRID_ROOT in project.parents:
        die("refusing to deploy into the-grid itself; its agents are wired globally by wire.sh")

    check_no_symlinks(project)
    lock = read_lock(project)
    roles = [r.strip() for r in args.roles.split(",") if r.strip()] if args.roles else (lock or {}).get("roles", [])
    profile = args.profile or (lock or {}).get("profile") or "lean"
    if not roles:
        die("no roles given and no lock file to take them from (use --roles, or --list to see options)")
    unknown = [r for r in roles if r not in index]
    if unknown:
        die(f"unknown role(s): {', '.join(unknown)} (see --list)")
    roles = sorted(set(roles))

    shared_ctx, role_ctx = load_context(project)
    stray = sorted(set(role_ctx) - set(roles))
    if stray:
        die(f"{project / CONTEXT_REL}: context for role(s) not being deployed: {', '.join(stray)}")

    files = render_all(roles, profile, index, shared_ctx, role_ctx)
    new_lock = lock_text(profile, roles, files)

    # Stale = previously deployed by us, no longer wanted.
    old_files = (lock or {}).get("files", {})
    stale = sorted(set(old_files) - set(files))

    # --- validate everything before touching anything -------------------------
    for rel in list(files) + stale:
        assert_inside(project, project / rel)       # before ANY write, so nothing is half-applied
    refused = [rel for rel in files if (project / rel).exists() and not is_generated(project / rel)]
    if refused:
        die("refusing to overwrite hand-written file(s) (no GENERATED marker):\n  "
            + "\n  ".join(refused) + "\n  move or rename them, or deploy under a different role set")

    # --- drift report ---------------------------------------------------------
    problems = []
    for rel, txt in sorted(files.items()):
        p = project / rel
        if not p.exists():
            problems.append(f"missing    {rel}")
        elif p.read_text(encoding="utf-8") != txt:
            problems.append(f"stale      {rel}")
    for rel in stale:
        if (project / rel).exists():
            problems.append(f"remove     {rel}")
    lock_path = project / LOCK_REL
    # The lock drifts when its content differs ignoring grid_commit: a new grid
    # commit with identical agents is not drift (and must not dirty the repo).
    def core(d: dict) -> dict:
        return {k: v for k, v in d.items() if k != "grid_commit"}
    lock_drift = not lock_path.exists() or core(lock or {}) != core(json.loads(new_lock))
    if lock_drift:
        problems.append(f"stale      {LOCK_REL}")

    if args.check:
        if problems:
            print(f"deploy --check: {project} differs from the grid:", file=sys.stderr)
            for line in problems:
                print(f"  {line}", file=sys.stderr)
            print("  fix: re-run deploy.py without --check", file=sys.stderr)
            sys.exit(1)
        print(f"deploy --check: {project} matches the grid ({len(files)} files, profile {profile}).")
        return

    if args.dry_run:
        print(f"[dry-run] {project}  profile={profile}  roles={','.join(roles)}")
        for rel, txt in sorted(files.items()):
            print(f"  write  {rel}  ({len(txt)} bytes)")
        for rel in stale:
            print(f"  remove {rel}")
        return

    # --- apply ----------------------------------------------------------------
    changed = 0
    for rel, txt in sorted(files.items()):
        p = project / rel
        assert_inside(project, p)
        if p.exists() and p.read_text(encoding="utf-8") == txt:
            continue
        atomic_write(p, txt)
        changed += 1
    for rel in stale:
        p = project / rel
        assert_inside(project, p)
        if p.exists() and is_generated(p):          # never delete a hand-edited file
            p.unlink()
            changed += 1
            if (p.parent.name.startswith(PREFIX + "-") or p.parent.name == "grid-reference") \
                    and not p.parent.is_symlink() and not any(p.parent.iterdir()):
                p.parent.rmdir()
    # Rewrite the lock only when its content (ignoring the commit hash) changed,
    # so a no-op re-run leaves every byte untouched.
    if lock_drift:
        assert_inside(project, lock_path)
        atomic_write(lock_path, new_lock)
        changed += 1
    print(f"deploy: {project}  profile={profile}  {len(files)} agent file(s), {changed} written.")


if __name__ == "__main__":
    main()
