#!/usr/bin/env bash
# worktree-setup.sh — idempotent per-worktree DB schema + port allocation.
#
# Each git worktree gets its own MySQL schema and APP_PORT, derived
# deterministically from the worktree's absolute path, so parallel
# autonomous agents never clash on a shared DB or port. Safe to re-run:
# the same worktree path always yields the same schema/port, and schema
# creation is IF NOT EXISTS.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WT_PATH="$(git -C "$PROJECT_ROOT" rev-parse --show-toplevel)"

HASH="$(printf '%s' "$WT_PATH" | cksum | cut -d' ' -f1)"
DB_NAME="lampapp_${HASH}"
APP_PORT=$((8000 + HASH % 1000))

ENV_LOCAL="$PROJECT_ROOT/.env.local"
cat > "$ENV_LOCAL" <<EOF
# Generated by scripts/worktree-setup.sh — do not edit by hand, do not commit.
DB_NAME=${DB_NAME}
APP_PORT=${APP_PORT}
EOF

ENV_FILE="$PROJECT_ROOT/.env"
[[ -f "$ENV_FILE" ]] || ENV_FILE="$PROJECT_ROOT/.env.example"
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

mysql -h "${DB_HOST:-127.0.0.1}" -P "${DB_PORT:-3306}" -u "${DB_USER:-root}" ${DB_PASS:+-p"$DB_PASS"} \
  -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`;"

echo "Worktree isolated: DB_NAME=${DB_NAME}  APP_PORT=${APP_PORT}  (written to .env.local)"
